PLINK: "/u/project/gandalm/shared/apps/plink"
#PLINK2: "/u/project/gandalm/shared/apps/plink2/v2.00a2-final/plink2"
MESC: "/u/project/gandalm/shared/apps/mesc/"
LDSC: "/u/project/gandalm/shared/apps/ldsc/"
GWAS_LIST:
- trait: PGC3_SCZ_wave3.european.autosome.public.v3
  file: /u/project/gandalm/shared/GWAS/SCZ.PGC3.2021/wave3_v3/PGC3_SCZ_wave3.european.autosome.public.v3
- trait: pgc-bip2021-all
  file: /u/project/gandalm/shared/GWAS/BIP.Mullins.2021/pgc-bip2021-all
- trait: ASD.iPSYCHPGC.2018
  file: /u/project/gandalm/shared/GWAS/ASD.Grove.iPSYCHPGC.2019/ASD.iPSYCHPGC.2018
- trait: ADHD.Demontis.2019
  file: /u/project/gandalm/shared/GWAS/ADHD.Demontis.PGC.2018/ADHD.Demontis.2019
- trait: MDD.Howard.PGC.2019
  file: /u/project/gandalm/shared/GWAS/MDD.Howard.PGC.2019/MDD.Howard.PGC.2019
- file: /u/project/gandalm/shared/GWAS/Intelligence.Savage.2018/Intelligence.SavageNatGen.2018
  trait: Intelligence.SavageNatGen.2018
- file: /u/project/gandalm/shared/GWAS/EduYears.Lee.SSGAC.2018/EduYears.SSGAC.Lee2018
  trait: EduYears.SSGAC.Lee2018
- file: /u/project/gandalm/shared/GWAS/ALZ.Jansen.2019/ALZ.Jansen.2019
  trait: ALZ.Jansen.2019
- file: /u/project/gandalm/shared/GWAS/Insomnia.Jansen.2018/Insomnia.Jansen.2018
  trait: Insomnia.Jansen.2018
