# Softwares
# add GEMMA for bslmm
GCTA: "/u/project/gandalm/shared/apps/gcta_1.93.0beta/gcta64"
PLINK: "/u/project/gandalm/shared/apps/plink2"
# Scripts
FUSION_SUSIE_SCRIPT: "/u/project/gandalm/cindywen/isoform_twas/TWAS/code/twas_susie_nmancuso/FUSION.compute_weights_wSusie.R"
FUSION_ASSOC_SCRIPT: "/u/project/gandalm/shared/TWAS/code/FUSION.assoc_test.R"
FUSION_POST_SCRIPT: "/u/project/gandalm/shared/TWAS/code/FUSION.post_process.R"
# LDREF
LDREF: "/u/project/gandalm/shared/TWAS/code/LDREF"

GWAS_LIST:
- file: /u/project/gandalm/shared/GWAS/SCZ.Pardinas.PGC.2018/SCZ.Clozuk.2018
  trait: SCZ.Clozuk.2018
# - file: /u/project/gandalm/shared/GWAS/ASD.Grove.iPSYCHPGC.2019/ASD.iPSYCHPGC.2018
#   trait: ASD.iPSYCHPGC.2018
# - file: /u/project/gandalm/shared/GWAS/Intelligence.Savage.2018/Intelligence.SavageNatGen.2018
#   trait: Intelligence.SavageNatGen.2018
# - file: /u/project/gandalm/shared/GWAS/EduYears.Lee.SSGAC.2018/EduYears.SSGAC.Lee2018
#   trait: EduYears.SSGAC.Lee2018
# - file: /u/project/gandalm/shared/GWAS/ALZ.Jansen.2019/ALZ.Jansen.2019
#   trait: ALZ.Jansen.2019
# - file: /u/project/gandalm/shared/GWAS/Insomnia.Jansen.2018/Insomnia.Jansen.2018
#   trait: Insomnia.Jansen.2018
# - file: /u/project/gandalm/shared/GWAS/BD.PGC3.2019/BD.PGC3
#   trait: BD.PGC3
# - file: /u/project/gandalm/shared/GWAS/MDD.Wray.PGC.2018/MDD.PGC.2018
#   trait: MDD.PGC.2018