# Softwares
# add GEMMA for bslmm
GCTA: "/u/project/gandalm/shared/apps/gcta_1.93.0beta/gcta64"
PLINK: "/u/project/gandalm/shared/apps/plink2/v2.00a2-final/plink2"
# Scripts
FUSION_SUSIE_SCRIPT: "/u/project/gandalm/cindywen/isoform_twas/TWAS/code/twas_susie_nmancuso/FUSION.compute_weights_wSusie.R"
FUSION_ASSOC_SCRIPT: "/u/project/gandalm/shared/TWAS/code/FUSION.assoc_test.R"
FUSION_POST_SCRIPT: "/u/project/gandalm/shared/TWAS/code/FUSION.post_process.R"
# LDREF
LDREF: "/u/project/gandalm/shared/TWAS/code/LDREF"

GWAS_LIST:
# - file: /u/project/gandalm/shared/GWAS/SCZ.Pardinas.PGC.2018/SCZ.Clozuk.2018
#   trait: SCZ.Clozuk.2018
# - file: /u/project/gandalm/shared/GWAS/SCZ.PGC3.2021/PGC3_SCZ_wave3_public.v2
#   trait: PGC3_SCZ_wave3_public.v2
- file: /u/project/gandalm/shared/GWAS/SCZ.PGC3.2021/wave3_v3/PGC3_SCZ_wave3.european.autosome.public.v3
  trait: PGC3_SCZ_wave3.european.autosome.public.v3

GWAS_N_LIST:
# - gwas_n: 161405
#   trait: PGC3_SCZ_wave3_public.v2
# - gwas_n: 107000
#   trait: SCZ.Clozuk.2018
# from paper, 175799*0.743. In EUR original sum stats, maximum NCA+NCON = 130644
- gwas_n: 130619
  trait: PGC3_SCZ_wave3.european.autosome.public.v3


